# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppCenterReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppCenterReactNative
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'AppCenterReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AppCenterReactNative-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AppCenterReactNative-tvOS

  target 'AppCenterReactNative-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
